type CountriesMap = {
    [key: string]: string;
};

const countries: CountriesMap = {
    'África do Sul': 'South Africa',
    'Alemanha': 'Germany',
    'Angola': 'Angola',
    'Arábia Saudita': 'Saudi Arabia',
    'Argentina': 'Argentina',
    'Austrália': 'Australia',
    'Áustria': 'Austria',
    'Bangladesh': 'Bangladesh',
    'Bélgica': 'Belgium',
    'Bolívia': 'Bolivia',
    'Bulgária': 'Bulgaria',
    'Cabo Verde': 'Cape Verde',
    'Canadá': 'Canada',
    'Chile': 'Chile',
    'China': 'China',
    'China, Hong Kong': 'China, Hong Kong',
    'Cingapura': 'Singapore',
    'Colômbia': 'Colombia',
    'Costa Rica': 'Costa Rica',
    'Croácia': 'Croatia',
    'Cuba': 'Cuba',
    'Dinamarca': 'Denmark',
    'Egito': 'Egypt',
    'El Salvador': 'El Salvador',
    'Equador': 'Ecuador',
    'Eslováquia': 'Slovakia',
    'Eslovênia': 'Slovenia',
    'Espanha': 'Spain',
    'Estados Unidos': 'United States',
    'Estônia': 'Estonia',
    'Filipinas': 'Philippines',
    'Finlândia': 'Finland',
    'França': 'France',
    'Gana': 'Ghana',
    'Grécia': 'Greece',
    'Guatemala': 'Guatemala',
    'Guiana': 'Guyana',
    'Guiana Francesa': 'French Guiana',
    'Haiti': 'Haiti',
    'Holanda': 'Netherlands',
    'Honduras': 'Honduras',
    'Hungria': 'Hungary',
    'Índia': 'India',
    'Indonésia': 'Indonesia',
    'Irã': 'Iran',
    'Iraque': 'Iraq',
    'Irlanda': 'Ireland',
    'Israel': 'Israel',
    'Itália': 'Italy',
    'Japão': 'Japan',
    'Letônia': 'Latvia',
    'Líbano': 'Lebanon',
    'Lituânia': 'Lithuania',
    'Luxemburgo': 'Luxembourg',
    'Malásia': 'Malaysia',
    'Marrocos': 'Morocco',
    'México': 'Mexico',
    'Moçambique': 'Mozambique',
    'Nicarágua': 'Nicaragua',
    'Nigéria': 'Nigeria',
    'Noruega': 'Norway',
    'Nova Zelândia': 'New Zealand',
    'Outros países': 'Other countries',
    'Outros países da África': 'Other African countries',
    'Outros países da América Central e Caribe': 'Other Central American and Caribbean countries',
    'Outros países da Ásia': 'Other Asian countries',
    'Outros países da Europa': 'Other European countries',
    'Outros países da Oceania': 'Other Oceanian countries',
    'Países não especificados': 'Unspecified countries',
    'Panamá': 'Panama',
    'Paquistão': 'Pakistan',
    'Paraguai': 'Paraguay',
    'Peru': 'Peru',
    'Polônia': 'Poland',
    'Porto Rico': 'Puerto Rico',
    'Portugal': 'Portugal',
    'Quênia': 'Kenya',
    'Reino Unido': 'United Kingdom',
    'República da Coreia': 'South Korea',
    'República Dominicana': 'Dominican Republic',
    'República Tcheca': 'Czech Republic',
    'Romênia': 'Romania',
    'Rússia': 'Russia',
    'Sérvia': 'Serbia',
    'Síria': 'Syria',
    'Suécia': 'Sweden',
    'Suíça': 'Switzerland',
    'Suriname': 'Suriname',
    'Tailândia': 'Thailand',
    'Taiwan': 'Taiwan',
    'Trinidad e Tobago': 'Trinidad and Tobago',
    'Tunísia': 'Tunisia',
    'Turquia': 'Turkey',
    'Ucrânia': 'Ukraine',
    'Uruguai': 'Uruguay',
    'Venezuela': 'Venezuela'
};

export default countries;